### ISSUE TITLE
Investigate map

### ISSUE THREAD

**Issue by olafveerman** [olafveerman/taxis#24]
Could we serve a simplified GeoJSON? Vector Tiles?

**Comment by olafveerman** [comment]
Looked into this and have a bash script up and running that ingests the data from [CAOP 2016](http://www.dgterritorio.pt/cartografia_e_geodesia/cartografia/carta_administrativa_oficial_de_portugal__caop_/caop_em_vigor/) and merges the freguesias of each concelho.

Resulting file sizes:

| format | ~ size in MB |
| --- | ---: |
| Shapefile | 26 |
| GeoJSON | 71 |
| TopoJSON | 40 |
| Simplified TopoJSON | 2 |

The impact on file size is pretty impressive, all the while retaining quite some detail. You can check it out here: https://gist.github.com/olafveerman/29e5bea855a01e03310ce3222f1f63b8

cc @leihla @danielfdsilva

**Comment by danielfdsilva** [comment]
Impressive indeed, and it retains a lot of detail. Should we simplify even further or does that become problematic?

**Comment by olafveerman** [comment]
Did some further simplification and added the result to the above table.
