### ISSUE TITLE
Data structure

### ISSUE THREAD

**Issue by danielfdsilva** [olafveerman/taxis#28]
@olafveerman 
This is the data we'll be needed for each page to build the charts. I'll also include an image of the charts we're planning to build. (it's a sketch on my notebook so may not be super clear)

### Homepage
  First part will be a summary of the year 2016 and we need an array with all districts with only the values for 2006 and 2016. **When the value of 2006 is not available we should use the next available year**.
- licença geral
- licença reduzida
- max licença geral
- max licença reduzida
- tipos de estacionamento (only for 2016)
- tipos de contingente (only for 2016)

Well also need to create a chart showing the change per year. For that we need the national aggregate of all years (2006 to 2016)
- licença geral
- licença reduzida
- max licença geral
- max licença reduzida

Last, we need some more generic information:
- Total taxis licença geral (for 2006 and 2016) [This is computable from other values. Is it worth to include?]
- Total taxis licença reduzida (for 2006 and 2016) [This is computable from other values. Is it worth to include?]
- Total number of distritos
- Total number of distritos - mobilidade reduzida (2006 and 2016)
- Total number of municipios
- Total number of municipios - mobilidade reduzida (2006 and 2016)

#### /national.json
```
{
  distritos: [
    {
      id
      name
      lic-geral: [
        {year: 2006, value: 1}
        {year: 2016, value: 1}
      ]
      lic-mob-reduzida: [
        {year: 2006, value: 1}
        {year: 2016, value: 1}
      ]
      max-lic-geral: [
        {year: 2006, value: 1}
        {year: 2016, value: 1}
      ]
      max-lic-mob-reduzida: [
        {year: 2006, value: 1}
        {year: 2016, value: 1}
      ]
      estacionamento: [livre, fixo]
      contingente: [a, b]
    }
    // ...
  ]
  national: {
    lic-geral: [
      {year: 2006, value: 1}
      // ...
    ]
    lic-mob-reduzida: [
      {year: 2006, value: 1}
      // ...
    ]
    max-lic-geral: [
      {year: 2006, value: 1}
      // ...
    ]
    max-lic-mob-reduzida: [
      {year: 2006, value: 1}
      // ...
    ]
    total-taxis: [
      {year: 2006, value: 1}
      {year: 2016, value: 1}
    ]
    total-lic-reduzida: [
      {year: 2006, value: 1}
      {year: 2016, value: 1}
    ]
    total-distritos: 20 // Total number of distritos
    total-distritos-reduzida: [ // Total number of distritos with taxis with licença mobilidade reduzida
      {year: 2006, value: 1}
      {year: 2016, value: 1}
    ]
    total-municipios: 309 // Total number of municípios
    total-municipios-reduzida: [ // Total number of municípios with taxis with licença mobilidade reduzida
      {year: 2006, value: 1}
      {year: 2016, value: 1}
    ]
  }
}
```

### Each distrito
The charts on the distrito page will be very similar to the ones on the homepage, only the data will differ.
We won't have a dedicated concelho page. Instead we'll have a table listing the concelhos of the distrito and show some info on it, including:
- change per year for both geral and reduzida
- types of estacionamento available 

We'll also have summary of the year 2016 and we need an array with all concelhos with values from 2006 to 2016.
- licença geral
- licença reduzida
- max licença geral
- max licença reduzida
- tipos de estacionamento (only for 2016)

We'll also be showing the change in time for the distrito being displayed. For that we need the district aggregate of all years (2006 to 2016).
- licença geral
- licença reduzida
- max licença geral
- max licença reduzida

Last, we need some more generic information:
- Total taxis licença geral (for 2006 and 2016) [This is computable from other values. Is it worth to include?]
- Total taxis licença reduzida (for 2006 and 2016) [This is computable from other values. Is it worth to include?]
- Total number of municipios
- Total number of municipios - mobilidade reduzida (2006 and 2016)

#### /[district-name].json
```
{
  concelhos: [
    {
      id
      name
      lic-geral: [
        {year: 2006, value: 1}
        // ...
      ]
      lic-mob-reduzida: [
        {year: 2006, value: 1}
        // ...
      ]
      max-lic-geral: [
        {year: 2006, value: 1}
        // ...
      ]
      max-lic-mob-reduzida: [
        {year: 2006, value: 1}
        // ...
      ]
      estacionamento: [livre, fixo]
    }
    // ...
  ]
  district: {
    lic-geral: [
      {year: 2006, value: 1}
      // ...
    ]
    lic-mob-reduzida: [
      {year: 2006, value: 1}
      // ...
    ]
    max-lic-geral: [
      {year: 2006, value: 1}
      // ...
    ]
    max-lic-mob-reduzida: [
      {year: 2006, value: 1}
      // ...
    ]
    total-taxis: [
      {year: 2006, value: 1}
      {year: 2016, value: 1}
    ]
    total-lic-reduzida: [
      {year: 2006, value: 1}
      {year: 2016, value: 1}
    ]
    total-municipios: 309 // Total number of municípios
    total-municipios-reduzida: [ // Total number of municípios with taxis with licença mobilidade reduzida
      {year: 2006, value: 1}
      {year: 2016, value: 1}
    ]
  }
}
```

Does this look reasonable to you?
Given the charts we have to build I think this is the most straightforward structure. If you have other thoughts let me know.

**Comment by danielfdsilva** [comment]
Here are the chart sketches

![image uploaded from ios](https://cloud.githubusercontent.com/assets/1090606/23533614/cbfd495a-ffaa-11e6-869b-225286993e27.jpg)

**Comment by olafveerman** [comment]
Thanks for this @danielfdsilva Will work on it.
Totally agree on the totals, these were already removed in: https://github.com/olafveerman/taxis/pull/23

**Comment by danielfdsilva** [comment]
@olafveerman Stop the presses!!!

After the last meeting some things changed which are reflected in the new mocks here: https://projects.invisionapp.com/share/TEAPCWCBG#/screens/221974968_Desktop_HD_-_V1

Basically a lot of information is now shown on a "concelho" level even though we're on the homepage.
As of right now the data we'd need is:

```
each distrito:
  - lic geral (from 2006 to 2016)
  - lic reduzida (from 2006 to 2016)
  - max licenças (only the total is needed in this case) (from 2006 to 2016)
  - population (2016 only)

  - each concelho:
    - lic geral (2006 and 2016)
    - lic reduzida (2006 and 2016)
    - types estacionamento
```
I think this is the bare minimum data we need to build the homepage. There will still be quite some data that needs to be computed client side, but can be done. My worry here is the file size. You think we'd be better off pre-processing everything and serving data per section?

The same data will be needed for the "distrito" page level.

**Comment by olafveerman** [comment]
Right on time.
Not sure if file size is a big issue here. `concelho.json` is 750kb with data for all years for:

```
lic-geral
lic-mob-reduzida
max-lic-geral
max-lic-mob-reduzida
pop-residente
```
