### ISSUE TITLE
Determine data structure

### ISSUE THREAD

**Issue by olafveerman** [olafveerman/taxis#3]
- one json? multiple?
- how to structure `data: {}`

**Comment by olafveerman** [comment]
We can use this as a starting point: https://raw.githubusercontent.com/olafveerman/taxis/api/data.json
@danielfdsilva

**Comment by danielfdsilva** [comment]
Maybe it's good to have a file per admin level? It's easier to have the values pre-aggregated.
I like the starting point. If we see that the file is too heavy, we can always create an index for `distritos`, but maybe is not worth it...

**Comment by olafveerman** [comment]
Yes, aggregation by admin level is tracked in #4.

Currently, the data is structured as follows:

```json
"data": {
  "1": {
    "2012": 61,
    "2013": 61,
    "2014": 61,
    "2015": 61,
    "2016": 61
  },
  "2": {
    "2012": 61,
    "2013": 61,
    "2014": 61,
    "2015": 61,
    "2016": 61
  }
}
```

Wondering if it makes sense to do this instead:

```json
"data": {
    "2012": {
        "1": 61,
        "2": 61
    },
    "2013": {
        "1": 61,
        "2": 61
    },
    "2014": {
        "1": 61,
        "2": 61
    }
}
```

**Comment by danielfdsilva** [comment]
I'd say it does. and instead of 1,2... we should come up with an identifier.

**Comment by olafveerman** [comment]
Yes to an identifier.

And capturing a conversation from Slack, we'll probably go with something like this:

```json
"data": [
  {
    "year": 2012,
    "1": 61,
    "2": 62
  }
]
```
