### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by olafveerman** [olafveerman/taxis#54]
Allow each concelho to have an annexed file:

- files will be uploaded to the `/files` folder
- in this folder, each admin area has its own folder. The folder name is equal to the id of the area, or has to start with the id followed by a hyphen.  Eg. `1204`, `1604-moncao`.
- the processing script will go through the folder and add the files to the metadata

Final result:

``` json
{
  "id": 1604,
  "name": "Monção",
  "type": "concelho",
  "files": [
    "files/1604-moncao/regulamento.pdf"
  ],
  "data": {}
}
```

cc @danielfdsilva

**Comment by danielfdsilva** [comment]
When there are no files the array will be empty right?

**Comment by olafveerman** [comment]
Yes, unless you prefer something else.

**Comment by danielfdsilva** [comment]
nope, that's perfect
