### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by olafveerman** [olafveerman/taxis#9]
Not all the concelhos seem to be included in the final dataset.

```
Aguiar da Beira
Alijó
Armamar
Barcelos
Barreiro
Borba
Chaves
Évora
Ferreira do Zêzere
Figueira da Foz
Funchal
Monchique
Montemor-o-Novo
Montemor-o-Velho
Murça
Nazaré
Ponta Delgada
Santa Cruz
Santana
Trofa
```

cc @leihla

**Comment by hmjbrito** [comment]
Já temos mais dados. Faltam apenas dados de: 
Trofa
Murça
Funchal (neste caso não é a câmara que os está a dar - é a secretaria regional da economia e transportes)
Instituto Mobilidade e dos Transportes (dados sobre táxis letra A e letra T)

Estamos a fazer pressão alta para conseguir os dados o mais depressa possível. Os dados mais difíceis penso que serão os do IMT.
Querem que vá enviando ficheiro à medida que temos novos dados ou é melhor enviar só no final quando tivermos tudo?

**Comment by olafveerman** [comment]
@hmjbrito 
Pode ser só no final. A ideia seria começar a gerir os dados no Github, neste ficheiro: https://github.com/olafveerman/taxis/blob/master/data/taxis.csv

**Comment by hmjbrito** [comment]
Um ponto em relação aos dados que o IMT disponibilizará (espero!) que pode ser importante para a estrutura do dataset final: 
Táxis letra A são licenciados por concelho;
Táxis Letra T são licenciados por zona turística: Porto, Lisboa e Faro. Zona turística do Porto inclui distritos do Porto, Braga e Viana do Castelo. Zona turística de Lisboa inclui distritos de Lisboa e Setúbal; Zona turística de Faro correspondente ao distrito de Faro.

**Comment by olafveerman** [comment]
Fantástico. Abri um issue aqui para as zonas turisticas. #19

**Comment by hmjbrito** [comment]
Têm que me explicar como faço o update (e o download) do csv
